### ISSUE TITLE
Use virtualenv and requirements.txt in setup instructions

### ISSUE THREAD

**Issue by matatk** [matatk/agrip#33]
This will make the process *a lot* simpler.

**Comment by francipvb** [comment]
Hi,

What about Docker? It should be even simpler ... It needs more resources than a virtualenv, though.

Cheers,

**Comment by matatk** [comment]
Thanks for the suggestion. Haven't used Docker before (so might be fun to learn).  The problem to be solved is to simplify the management of third-party libraries that are needed for development.  Virtualenv is focused solely on this, so it's a natural fit, but I will check out Docker too.

I'm working on some improvements in [the `mac-build` branch](https://github.com/matatk/agrip/tree/mac-build) and have moved to using "requirements.txt" to specify dependencies.  That addresses the problem of making development environments consistent and easy to set up.  But I think that soon it will also be necessary to isolate the environment for AudioQuake from other projects people may be working on.

**Comment by francipvb** [comment]
I was thinking more about docker and I found a problem. It can only produce linux builds in all platforms. To build windows or mac releases it needs native container support.

Using windows hosted CI it can build windows programs too but I don't know so much about it.

About Mac native containers I don't know anithing, but MacOSX native containers are supported too.

See this [link](http://talkincloud.com/cloud-computing/docker-unveils-native-container-support-windows-and-mac-os-x).

With [this](https://www.appveyor.com/) for Windows and [this](https://travis-ci.org/) for linux and Mac you have a complete hosted toolkit to test and build releases for major platforms using CI.

Ope this helps.

Cheers,

**Comment by matatk** [comment]
This was closed by #44.
